import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Baseline schema.
 *
 * `stall_designer_db` did not exist when this was written (verified 2026-09-19), so this is a
 * fresh schema derived from the Java entity mappings (docs/03-database-model.md), with three
 * deliberate differences, all logged as ADR-016:
 *
 *  1. Identity sequences start at 1000. Both frontends ship starter halls with ids 1 and 2 and
 *     treat a saved hall with the same id as "the same hall" (docs/11 G-5). Starting at 1000
 *     removes the collision without touching the frontend or the API contract.
 *  2. `stalls.layout_id` is NOT NULL. It was nullable in the Java schema only because Hibernate
 *     inserted the row first and set the FK with a second UPDATE.
 *  3. `stalls.layout_id` is indexed (docs/03 P-02).
 */
export class Baseline1758240000000 implements MigrationInterface {
  name = 'Baseline1758240000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // IF NOT EXISTS everywhere: with migrationsRun enabled this baseline must be a no-op
    // on a database whose schema already exists without a TypeORM history table.
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS hall (
        id      bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
        name    varchar(255),
        shape   varchar(255),
        width   double precision,
        length  double precision,
        radius  double precision
      )
    `);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS layouts (
        id           bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
        name         varchar(255)     NOT NULL,
        hall_width   double precision NOT NULL,
        hall_length  double precision NOT NULL,
        hall_height  double precision NOT NULL,
        hall_id      bigint,
        CONSTRAINT uq_layouts_hall_id UNIQUE (hall_id),
        CONSTRAINT fk_layouts_hall FOREIGN KEY (hall_id) REFERENCES hall (id)
      )
    `);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS stalls (
        id         bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
        name       varchar(255),
        width      double precision NOT NULL,
        length     double precision NOT NULL,
        height     double precision NOT NULL,
        posx       double precision NOT NULL,
        posz       double precision NOT NULL,
        color      varchar(255),
        gate_side  varchar(255),
        layout_id  bigint NOT NULL,
        CONSTRAINT fk_stalls_layout FOREIGN KEY (layout_id) REFERENCES layouts (id)
      )
    `);

    await queryRunner.query(`CREATE INDEX IF NOT EXISTS idx_stalls_layout_id ON stalls (layout_id)`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE stalls`);
    await queryRunner.query(`DROP TABLE layouts`);
    await queryRunner.query(`DROP TABLE hall`);
  }
}
