import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Stall-plotting rules written by planners, in their own words, and the halls they apply to.
 *
 * `applies_to_all` is a flag rather than one link row per hall, so a rule marked "all halls"
 * also covers halls imported after it was written. Otherwise `planner_rule_halls` lists the
 * halls; deleting a hall or a rule removes its links (ON DELETE CASCADE).
 */
export class AddPlannerRules1758240800000 implements MigrationInterface {
  name = 'AddPlannerRules1758240800000';

  async up(q: QueryRunner): Promise<void> {
    await q.query(`
      CREATE TABLE IF NOT EXISTS planner_rules (
        id              bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
        description     text        NOT NULL,
        applies_to_all  boolean     NOT NULL DEFAULT false,
        created_at      timestamptz NOT NULL DEFAULT now(),
        updated_at      timestamptz NOT NULL DEFAULT now()
      )
    `);
    await q.query(`
      CREATE TABLE IF NOT EXISTS planner_rule_halls (
        rule_id  bigint NOT NULL REFERENCES planner_rules (id) ON DELETE CASCADE,
        hall_id  bigint NOT NULL REFERENCES hall (id) ON DELETE CASCADE,
        PRIMARY KEY (rule_id, hall_id)
      )
    `);
    await q.query(
      `CREATE INDEX IF NOT EXISTS idx_planner_rule_halls_hall_id ON planner_rule_halls (hall_id)`,
    );
  }

  async down(q: QueryRunner): Promise<void> {
    await q.query(`DROP TABLE IF EXISTS planner_rule_halls`);
    await q.query(`DROP TABLE IF EXISTS planner_rules`);
  }
}
