import { MigrationInterface, QueryRunner } from 'typeorm';
export class PricingMasters1791030000000 implements MigrationInterface {
  async up(q: QueryRunner): Promise<void> {
    await q.query(`CREATE TABLE IF NOT EXISTS price_masters (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name varchar(120) NOT NULL, revision integer NOT NULL DEFAULT 1, policy jsonb NOT NULL
    )`);
    await q.query('CREATE UNIQUE INDEX IF NOT EXISTS price_masters_name_key ON price_masters (lower(name))');
    await q.query('ALTER TABLE layouts ADD COLUMN IF NOT EXISTS pricing_policy jsonb');
    await q.query('ALTER TABLE stalls ADD COLUMN IF NOT EXISTS booking_quote jsonb');
  }
  async down(q: QueryRunner): Promise<void> {
    await q.query('ALTER TABLE stalls DROP COLUMN IF EXISTS booking_quote');
    await q.query('ALTER TABLE layouts DROP COLUMN IF EXISTS pricing_policy');
    await q.query('DROP TABLE IF EXISTS price_masters');
  }
}
