import 'reflect-metadata';

import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import { Logger } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';

import { AppModule } from '../src/app.module';
import { HallService } from '../src/halls/hall.service';
import type { HallDto } from '../src/layouts/dto/layout-save-request.dto';
import type { BlockedArea } from '../src/layouts/entities/hall.entity';

/**
 * Seeds the demo database with halls copied from the real ITPO/Pragati Maidan production data.
 *
 * WHY THIS EXISTS
 * The planner used to start from two invented halls hardcoded in the Angular store
 * ("Main Exhibition Hall A", "Premium Circular Lounge"). Neither exists anywhere. The client
 * demo should show real halls, so these rows are lifted from the production database instead of
 * being made up.
 *
 * PROVENANCE — every row below was read from the `bm_prod` dump (`15-09.sql`), schema `idp`:
 *   - the hall is a real `T_HALLS` row with `is_active = true`
 *   - it has exactly one real `T_HALL_LAYOUTS` row with `status = 1`
 *   - `width`/`length` come from that layout's `length`/`breadth`
 *
 * The `length` -> width and `breadth` -> length mapping was verified, not assumed: for all 23
 * layouts carrying `nonClickableAreas`, the maximum X extent matches `length` and the maximum Y
 * extent matches `breadth`.
 *
 * NOTHING IN PRODUCTION IS READ AT RUNTIME OR WRITTEN TO. These are literals, and they are
 * written only to the demo database this backend is pointed at.
 *
 * Run with:  npm run seed:demo-halls [-- --refresh]
 * Idempotent: a hall whose name already exists is skipped, so re-running never duplicates.
 * With --refresh an existing hall keeps its id and gets the current geometry (boundary, zones,
 * markers, rules) — for a database seeded before those fields existed.
 */

interface DemoHall {
  name: string;
  width: number;
  length: number;
  /** Where this came from, so the row can always be traced back. */
  source: string;
}

/** One hall's geometry from demo-hall-shapes.json. Every field but blockedAreas may be absent. */
type DemoHallGeometry = Pick<
  HallDto,
  'blockedAreas' | 'boundary' | 'zones' | 'openings' | 'markers' | 'rules'
>;

interface DemoHallShapesFile {
  halls: Record<string, DemoHallGeometry & { blockedAreas: BlockedArea[] }>;
}

/**
 * Irregular-hall geometry per demo hall name, generated by
 * `scripts/build-demo-hall-shapes.ts` from T_EVENT_HALL_LAYOUT_DATA.csv.
 * Missing entry -> the hall is seeded as a plain rectangle, as before.
 */
function loadGeometry(): Map<string, DemoHallGeometry> {
  const file = JSON.parse(
    readFileSync(join(__dirname, 'data', 'demo-hall-shapes.json'), 'utf-8'),
  ) as DemoHallShapesFile;

  return new Map(
    Object.entries(file.halls).map(([name, shape]) => [
      name,
      {
        blockedAreas: shape.blockedAreas,
        boundary: shape.boundary ?? null,
        zones: shape.zones ?? null,
        openings: shape.openings ?? null,
        markers: shape.markers ?? null,
        rules: shape.rules ?? null,
      },
    ]),
  );
}

/**
 * Five halls of deliberately different proportions, so the demo can show a large hall, a small
 * one and a long narrow one without inventing anything.
 *
 * No circular hall is seeded: production has none. Circular halls are still demonstrable live
 * through the "Create Hall" form, which is the honest way to show that feature.
 */
const DEMO_HALLS: readonly DemoHall[] = [
  { name: 'Hall 1GF', width: 84, length: 116, source: 'T_HALLS.id=49, T_HALL_LAYOUTS.id=23' },
  { name: 'Hall 2GF', width: 70, length: 90, source: 'T_HALLS.id=51, T_HALL_LAYOUTS.id=25' },
  { name: 'Hall 12', width: 58, length: 41, source: 'T_HALLS.id=65, T_HALL_LAYOUTS.id=32' },
  { name: 'Hall 8-9-10', width: 133, length: 43, source: 'T_HALLS.id=63, T_HALL_LAYOUTS.id=36' },
  {
    name: 'Convention Center',
    width: 61,
    length: 60,
    source: 'T_HALLS.id=78, T_HALL_LAYOUTS.id=40',
  },
];

async function seed(): Promise<void> {
  const logger = new Logger('SeedDemoHalls');
  // 'log' is included so this script's own progress lines are not filtered out.
  const app = await NestFactory.createApplicationContext(AppModule, {
    logger: ['log', 'warn', 'error'],
  });

  try {
    const halls = app.get(HallService);
    const refresh = process.argv.includes('--refresh');
    const existing = new Map((await halls.list()).map((hall) => [hall.name, hall]));
    const geometryByName = loadGeometry();

    let created = 0;
    let skipped = 0;

    for (const demo of DEMO_HALLS) {
      const found = existing.get(demo.name);
      if (found && refresh) {
        await halls.update(found.id, {
          name: demo.name,
          shape: 'SQUARE',
          width: demo.width,
          length: demo.length,
          radius: 0,
          ...(geometryByName.get(demo.name) ?? { blockedAreas: [] }),
        });
        logger.log(`update ${demo.name} (id ${found.id}) — geometry refreshed`);
        skipped++;
        continue;
      }
      if (found) {
        logger.log(`skip   ${demo.name} — already present`);
        skipped++;
        continue;
      }

      // Through HallService, so the seed cannot write a hall the API would reject (ADR-015).
      const hall = await halls.create({
        name: demo.name,
        shape: 'SQUARE',
        width: demo.width,
        length: demo.length,
        radius: 0,
        ...(geometryByName.get(demo.name) ?? { blockedAreas: [] }),
      });

      logger.log(`create ${hall.name} (id ${hall.id}) ${demo.width}x${demo.length} — ${demo.source}`);
      created++;
    }

    logger.log(`done — ${created} created, ${skipped} skipped`);
  } finally {
    await app.close();
  }
}

void seed().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
