import { NestFactory } from '@nestjs/core';
import { Logger } from '@nestjs/common';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import { AppModule } from '../src/app.module';
import { HallService } from '../src/halls/hall.service';

/**
 * Fills in the `amenities` column for every hall the SelfCare export has icons for.
 *
 * Run with:  npm run seed:hall-amenities
 *
 * WHY THIS IS SEPARATE FROM seed-demo-halls
 * -----------------------------------------
 * Only five halls have geometry generated by build-demo-hall-shapes; the rest were created
 * some other way. Folding their icons into that seeder would mean also writing geometry this
 * project did not produce, overwriting whatever is live. So this script reads each hall as it
 * is, changes ONLY `amenities`, and writes every other field straight back.
 *
 * It targets standalone halls (`list(true)`) — the same set `GET /api/halls?standalone=true`
 * serves to the planner. Every saved layout keeps a private copy of its hall under the same
 * name (BR-18), and writing to one of those puts the icons somewhere no frontend loads.
 */
interface AmenitiesFile {
  _provenance: string;
  halls: Record<
    string,
    Array<{
      kind: string;
      label: string;
      position: { x: number; z: number };
      anchor?: { x: number; z: number };
      slot?: number;
    }>
  >;
}

async function seed(): Promise<void> {
  const logger = new Logger('seed-hall-amenities');
  const app = await NestFactory.createApplicationContext(AppModule, {
    logger: ['log', 'warn', 'error'],
  });

  try {
    const halls = app.get(HallService);
    const file = JSON.parse(
      readFileSync(join(__dirname, 'data', 'hall-amenities.json'), 'utf-8'),
    ) as AmenitiesFile;

    // Lowest id per name: the original master, not a later duplicate.
    const byName = new Map<string, { id: number }>();
    for (const hall of await halls.list(true)) {
      if (hall.name === null) continue;
      const seen = byName.get(hall.name);
      if (!seen || hall.id < seen.id) byName.set(hall.name, hall);
    }

    let updated = 0;
    let missing = 0;

    for (const [name, amenities] of Object.entries(file.halls)) {
      const target = byName.get(name);
      if (!target) {
        logger.warn(`skip   ${name} — no standalone hall with this name`);
        missing++;
        continue;
      }

      // Read back in full, so everything except `amenities` is written exactly as it stands.
      const current = await halls.get(target.id);
      await halls.update(target.id, {
        name: current.name,
        shape: current.shape,
        width: current.width,
        length: current.length,
        radius: current.radius,
        blockedAreas: current.blockedAreas,
        boundary: current.boundary,
        zones: current.zones,
        openings: current.openings,
        markers: current.markers,
        compass: current.compass,
        legends: current.legends,
        rules: current.rules,
        amenities,
      });

      logger.log(`update ${name} (id ${target.id}) — ${amenities.length} amenities`);
      updated++;
    }

    logger.log(`done: ${updated} hall(s) updated, ${missing} not found`);
  } finally {
    await app.close();
  }
}

seed().catch((error) => {
  new Logger('seed-hall-amenities').error(error instanceof Error ? error.stack : String(error));
  process.exitCode = 1;
});
